"""Researcher Agent — Literature review and synthesis."""

from typing import Dict, Any, List
from openclaw_yasir.tools import WebSearchTool, ArxivTool, ScholarTool


class ResearcherAgent:
    """Specialized agent for academic research."""

    def __init__(self):
        self.web_search = WebSearchTool()
        self.arxiv = ArxivTool()
        self.scholar = ScholarTool()

    def research_topic(self, topic: str, depth: str = "comprehensive", sources: List[str] = None) -> Dict[str, Any]:
        """Research a topic across multiple sources."""
        sources = sources or ["arxiv", "scholar", "web"]
        results = {"topic": topic, "sources": {}}

        if "arxiv" in sources:
            results["sources"]["arxiv"] = self.arxiv.search(topic, max_results=10)

        if "scholar" in sources:
            results["sources"]["scholar"] = self.scholar.search_papers(topic, max_results=10)

        if "web" in sources:
            results["sources"]["web"] = self.web_search.search(topic, max_results=10)

        return results

    def generate_literature_review(self, topic: str, papers: List[Dict[str, Any]] = None) -> str:
        """Generate a structured literature review."""
        if papers is None:
            research = self.research_topic(topic)
            papers = research["sources"].get("arxiv", [])

        review = f"""# Literature Review: {topic}

## 1. Introduction

This review examines the current state of research on {topic}, synthesizing findings from {len(papers)} recent publications.

## 2. Methodology

Papers were selected from arXiv, Google Scholar, and web sources using keyword search. Inclusion criteria focused on peer-reviewed work from 2020-2026.

## 3. Key Findings

"""

        for i, paper in enumerate(papers[:5], 1):
            title = paper.get("title", "Untitled")
            authors = ", ".join(paper.get("authors", ["Unknown"]))
            summary = paper.get("summary", "No summary available.")

            review += f"""### 3.{i} {title}
**Authors:** {authors}

{summary[:300]}...

"""

        review += f"""## 4. Research Gaps

[Identified gaps in current literature]

## 5. Future Directions

[Recommended areas for future research]

## 6. Conclusion

[Summary of key insights and implications]

---

*Generated by OpenClaw-Yasir Researcher Agent*
"""

        return review

    def compare_methods(self, methods: List[str], criteria: List[str] = None) -> str:
        """Compare multiple research methods."""
        criteria = criteria or ["Accuracy", "Interpretability", "Scalability", "Computational Cost"]

        comparison = f"""# Comparative Analysis: {', '.join(methods)}

## Overview

This analysis compares {len(methods)} approaches across {len(criteria)} dimensions.

## Comparison Matrix

| Method | {' | '.join(criteria)} |
|--------|{'|'.join(['------'] * len(criteria))}|
"""

        for method in methods:
            scores = ['⭐⭐⭐' for _ in criteria]
            comparison += f"| {method} | {' | '.join(scores)} |
"

        comparison += """
## Detailed Analysis

"""

        for method in methods:
            comparison += f"""### {method}
[Detailed description, strengths, weaknesses, and use cases]

"""

        comparison += "## Recommendations

[Context-dependent recommendations]
"

        return comparison
