"""Reviewer Agent — Peer review and quality assurance."""

from typing import Dict, Any, List


class ReviewerAgent:
    """Specialized agent for peer review of research papers and code."""

    def __init__(self):
        self.review_criteria = {
            "paper": ["novelty", "methodology", "clarity", "relevance", "citations"],
            "code": ["readability", "efficiency", "security", "testing", "documentation"],
            "article": ["engagement", "accuracy", "structure", "seo", "voice"]
        }

    def review_paper(self, paper_text: str, criteria: List[str] = None) -> Dict[str, Any]:
        """Review a research paper."""
        criteria = criteria or self.review_criteria["paper"]

        review = {
            "overall_score": 0,
            "criteria_scores": {},
            "strengths": [],
            "weaknesses": [],
            "recommendations": [],
            "verdict": ""
        }

        # Check for key sections
        sections = ["abstract", "introduction", "methodology", "results", "conclusion", "references"]
        missing_sections = [s for s in sections if s.lower() not in paper_text.lower()]

        if missing_sections:
            review["weaknesses"].append(f"Missing sections: {', '.join(missing_sections)}")
        else:
            review["strengths"].append("Well-structured with all standard sections")

        # Check citations
        citation_count = paper_text.count("[") + paper_text.count("(")
        if citation_count < 5:
            review["weaknesses"].append("Insufficient citations — aim for 10+ references")
        else:
            review["strengths"].append(f"Adequate citation count ({citation_count}+)")

        # Check word count
        word_count = len(paper_text.split())
        if word_count < 2000:
            review["weaknesses"].append(f"Paper is too short ({word_count} words). Aim for 3000-8000 words")
        elif word_count > 12000:
            review["weaknesses"].append(f"Paper may be too long ({word_count} words). Consider condensing")
        else:
            review["strengths"].append(f"Appropriate length ({word_count} words)")

        # Calculate score
        base_score = 70
        base_score += len(review["strengths"]) * 5
        base_score -= len(review["weaknesses"]) * 8
        review["overall_score"] = max(0, min(100, base_score))

        # Verdict
        if review["overall_score"] >= 80:
            review["verdict"] = "ACCEPT — Minor revisions suggested"
        elif review["overall_score"] >= 60:
            review["verdict"] = "MAJOR REVISION — Address weaknesses before resubmission"
        else:
            review["verdict"] = "REJECT — Significant improvements needed"

        review["recommendations"] = [
            "Ensure all claims are backed by evidence",
            "Add more recent references (2023-2026)",
            "Improve figure/table captions",
            "Consider adding a limitations section"
        ]

        return review

    def generate_review_report(self, review_data: Dict[str, Any], paper_title: str = "Untitled") -> str:
        """Generate a formatted review report."""

        report = f"""# Peer Review Report

**Paper:** {paper_title}
**Reviewer:** Yasir the Critic (OpenClaw-Yasir Reviewer Agent)
**Date:** 2026
**Verdict:** {review_data['verdict']}

---

## Overall Score: {review_data['overall_score']}/100

{'🟢 Strong Accept' if review_data['overall_score'] >= 80 else '🟡 Accept with Revisions' if review_data['overall_score'] >= 60 else '🔴 Reject'}

---

## ✅ Strengths

"""

        for strength in review_data["strengths"]:
            report += f"- {strength}
"

        report += "
## ❌ Weaknesses

"

        for weakness in review_data["weaknesses"]:
            report += f"- {weakness}
"

        report += "
## 💡 Recommendations

"

        for i, rec in enumerate(review_data["recommendations"], 1):
            report += f"{i}. {rec}
"

        report += """
---

## Reviewer Notes

This review was generated by the OpenClaw-Yasir Reviewer Agent, trained on peer review standards for USJICT and IJCNS journals. For human validation, please consult a senior researcher in your field.

---

*"Constructive criticism is the highest form of respect."*
"""

        return report
